# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b680501d5acdd8512de9a8dcba23d90ec7eb35de79d720010afef6263441a5ce87b2b7b523bbfb32bf4ef600cef6ac9017468b4ff9db62dbe77e260f0fcdda6
  github_client_id: 8f9ad6513fc5bdb3310c
  github_client_secret: 8f4e866663c8384e13e5e2fa26a765736e1ec128

test:
  secret_key_base: c017917d5928b010f21d668bd95218ff2bf8fbfd7369ba17141b1d6d3deec8f6a1f596eee1c5890258582e60caac8860f54385379de72a04ffadadfa099d34fe
  github_client_id: 8f9ad6513fc5bdb3310c
  github_client_secret: 8f4e866663c8384e13e5e2fa26a765736e1ec128
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_client_id: 8f9ad6513fc5bdb3310c
  github_client_secret: 8f4e866663c8384e13e5e2fa26a765736e1ec128
